//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionStrategy.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OptionStrategy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a yyyyMMdd.
        /// </summary>
        internal static string dateFormat {
            get {
                return ResourceManager.GetString("dateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 0.00.
        /// </summary>
        internal static string doubleFormat {
            get {
                return ResourceManager.GetString("doubleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CLOSED.
        /// </summary>
        internal static string marketStatusClosed {
            get {
                return ResourceManager.GetString("marketStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OPEN.
        /// </summary>
        internal static string marketStatusOpen {
            get {
                return ResourceManager.GetString("marketStatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AAL
        ///ABX
        ///AEO
        ///BAC
        ///BBRY
        ///BBY
        ///BX
        ///COH
        ///COP
        ///CSCO
        ///DDD
        ///EBAY
        ///EEM
        ///EWS
        ///EWW
        ///EWZ
        ///FCX
        ///GDX
        ///GE
        ///GG
        ///GM
        ///GNC
        ///GPRO
        ///GPS
        ///GRPN
        ///HLF
        ///HPQ
        ///INTL
        ///JCP
        ///JNPR
        ///KO
        ///KORS
        ///MS
        ///MU
        ///NCR
        ///OIH
        ///ORCL
        ///P
        ///PBR
        ///PFE
        ///POT
        ///RIG
        ///RSX
        ///SLV
        ///T
        ///TBT
        ///TRIP
        ///TWTR
        ///UNG
        ///URBN
        ///USO
        ///VXX
        ///VZ
        ///WFM
        ///WMB
        ///X
        ///XHB
        ///XLF
        ///XLU
        ///XOP
        ///XRT
        ///YELP
        ///YHOO
        ///ZNGA
        ///.
        /// </summary>
        internal static string tickersList {
            get {
                return ResourceManager.GetString("tickersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Call.
        /// </summary>
        internal static string typeCall {
            get {
                return ResourceManager.GetString("typeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OPT.
        /// </summary>
        internal static string typeOption {
            get {
                return ResourceManager.GetString("typeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Put.
        /// </summary>
        internal static string typePut {
            get {
                return ResourceManager.GetString("typePut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a STK.
        /// </summary>
        internal static string typeStock {
            get {
                return ResourceManager.GetString("typeStock", resourceCulture);
            }
        }
    }
}
